In [1]:
import numpy as np

In [8]:
y_pred = np.random.randint(1,19,5)

In [9]:
y= np.random.randint(1,19,5)

In [10]:
y

array([ 5, 17, 13,  1,  6])

# Regression cost functions

# mean squared error

In [11]:
np.mean((y_pred-y)**2) ## differentiable at 0

np.float64(19.8)

## root mean squared error

In [13]:
np.power(np.mean((y_pred-y)**2),1/2) ## differentiate at 0

np.float64(4.449719092257398)

## mean absolute error

In [16]:
np.mean(abs(y_pred-y))  ## differentiable at 0

np.float64(3.8)

## log cosh loss

In [17]:
np.mean(np.log(np.cosh(y_pred -y)))

np.float64(3.246053719939687)

## Huber loss

## huber loss = mse + map 

In [27]:
threshold =1 #setting threshold above is higher error and below this threshold is lower error 
abs_error = np.abs(y_pred, y)
# mse
capped_error = np.minimum(abs_error, threshold)
mse = 0.5*capped_error**2

# map
mae = threshold*(abs_error - (0.5*threshold))

huber_loss = np.mean(mae +mse)
huber_loss

np.float64(10.2)

In [24]:
np.minimum(np.abs(y_pred-y), 1)

array([1, 1, 1, 0, 1])

# classification cost function

## binary cross entropy

In [42]:
y = np.array([0,0,0,1,1,1])
prob = np.array([0.2,0.3,0.4,0.9,0,0.45])

In [47]:
eps = 1e-15
prob_clipped = np.clip(prob, eps, 1 - eps)
cross_entropy = -np.sum(y*np.log2(prob_clipped) + (1-y)*np.log2(1-prob_clipped))
cross_entropy

np.float64(52.706394472083865)

## category cross entropy for more than two class



In [52]:
a = np.array([[1,0,0], [0,1,0],[0,0,1]])
prob = np.array([
    [0.7, 0.2, 0.1],
    [0.3, 0.4, 0.3],
    [0.2, 0.5, 0.3]
])


In [53]:
prob_clipped = np.clip(prob, eps, 1 - eps)


In [54]:
prob_clipped

array([[0.7, 0.2, 0.1],
       [0.3, 0.4, 0.3],
       [0.2, 0.5, 0.3]])

In [59]:
cat_crs_ent = -np.sum(a * np.log2(prob_clipped)) ## element wise multiplication a(ij) * prob_clipped(ij)

In [60]:
cat_crs_ent

np.float64(3.573466861883327)

## categorical sparse entropy

In [62]:
## application in real life scenarios like class are classified as 1,2,3,4

In [75]:
y = np.array([2,1,0])
y_pred = np.array([[0.4 ,0.2 , 0.4] , [0.3 , 0.3 , 0.4] , [0.1,0.89 , 0.01]])


In [81]:
eps = 1e-15
cliped_pred = np.clip(y_pred , eps , 1-eps)
prob =  y_pred[np.arange(len(y)),y]  # matrix indexing y_pred [[0,1,2],[2,1,0]] -> returns maps this into (0,1) , (1,2) , (2,0)
cat_spa_loss = np.mean(-np.log(prob))
cat_spa_loss

np.float64(1.4742828763980456)

In [80]:
np.arange(len(y))
            #y_true)

array([0, 1, 2])

In [79]:
y_pred[
            np.arange(len(y)),
            y
        ]

array([0.4, 0.3, 0.1])

In [70]:
 np.arange(len(y))

array([0, 1, 2])

## Hinge loss

In [83]:
y= np.array([-1,1,-1,1])
decision_score = [100 , 0.5 , 0 , -5000]
hinge_loss = np.mean(np.maximum(0,1-(y*decision_score)))
hinge_loss

np.float64(1275.875)

## Focal loss

In [88]:
alpha = 0.2
gamma = 2
y = np.array([1,1,1 ,0])
true_prob= np.array([0.6,0.7,0.2,0.6])
pt = np.where(y==1 ,true_prob, 1-true_prob)

In [89]:
pt

array([0.6, 0.7, 0.2, 0.4])

In [92]:
focal_loss = np.mean(-alpha*((1-pt)**gamma)*np.log(pt))

In [93]:
focal_loss

np.float64(0.07368688860947824)

# Clustering techniques

## within cluster sum of square

In [95]:
x = np.array([[0,1],[1,2],[3,4] , [4,3]])
labels = np.array([1,2,2,1])
centroid = {1 : [1,2] , 2: [3,3]}


In [99]:
total=0
for i in range(len(x)):
    total += np.sum((x[i]-centroid[labels[i]])**2)


In [100]:
total

np.int64(18)

## sillohutte score

In [111]:
X = np.array([[1,2],[2,3],[3,4],[3,5]])
label = np.array([1,1,2,2])
def equalidian_dist(x1,x2):
    return np.sqrt(np.sum((x1-x2)**2))

def intradistance_btw_cluster(X,label,idx):
    cur_idx = np.where(label == label[idx])[0]
    cur_idx = cur_idx[cur_idx != idx]
    cur_clu = X[cur_idx]
    total = 0
    for each in cur_clu:
        total += equalidian_dist(X[idx],each)
    return total/len(cur_clu)
def nearest_cluster_distance(X, label , idx):
    labels_uni = np.unique(label)
    other_cluster = labels_uni[labels_uni != label[idx]]    
    min_dist = np.inf
    for clu in other_cluster:
        cur_clu_idx = np.where(label==clu)[0]
        cur_clu = X[cur_clu_idx]
        total=0
        for each in cur_clu:
            total+= equalidian_dist(each , X[idx])
        avg = total/len(cur_clu)
        min_dist = min(avg , min_dist)
    return min_dist
    
s =0
for idx in range(len(X)):
    a = intradistance_btw_cluster(X,label,idx)
    b  = nearest_cluster_distance(X,label, idx)
    s += (b-a)/max(b,a)
sillohutte_score = s/len(X)
sillohutte_score
        

np.float64(0.4929412689588045)

## Davies -  bouldin index

In [120]:
X = np.array([[1,2],[2,3],[3,4],[3,3]])
label = np.array([0,0,1,1])
centroid = {0:np.array([2,2]),1:np.array([3,3])}
def scatterred_dist(X,centroid , idx,label):
    cur_clu_idx = np.where(label==label[idx])[0]
    points = X[cur_clu_idx]
    total=0
    dbi = 0
    for p in points:
        total+=equalidian_dist(p,centroid)
    return total/len(points)
def davis_bouldin_index():
    cluster = np.unique(label)
    R = []
    for i in cluster:
        max_similarity = -np.inf
        s_i = scatterred_dist(X,centroid[i],i,label)
        for j in cluster:
            if i == j:
                continue
            s_j = scatterred_dist(X, centroid[j],j,label)
            mij = equalidian_dist(centroid[i],centroid[j])
            dbi  = (s_i+s_j)/mij
            max_similarity = max(max_similarity,dbi)
        R.append(max_similarity)
    return np.mean(R)
davis_bouldin_index()            
    

np.float64(1.851229586821916)