In [1]:
import numpy as np
import scipy.linalg as la

# Vector operations

## vector creations

In [2]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])


In [3]:
zeros = np.zeros(5)

In [4]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
#create random vector
np.random.rand(3)

array([0.60802494, 0.8375417 , 0.21131045])

In [6]:
v1.shape , v2.shape

((3,), (3,))

In [7]:
zeros.shape

(5,)

## vector indexing

In [8]:
v1[0]

np.int64(1)

In [9]:
v2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [10]:
v2[-1]

np.int64(6)

## vector slicing

In [11]:
v = np.array([10,20,30,40,50])


In [12]:
v[:3]

array([10, 20, 30])

In [13]:
v[:]

array([10, 20, 30, 40, 50])

In [14]:
v[2:]

array([30, 40, 50])

In [15]:
v[-1:]

array([50])

In [16]:
v[-3:]

array([30, 40, 50])

In [17]:
v[:-3]

array([10, 20])

## Arithematic operations

In [18]:
v1+v2

array([5, 7, 9])

In [19]:
v1 + np.array([0, 1])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [20]:
v1 -v2

array([-3, -3, -3])

In [21]:
v2-v1

array([3, 3, 3])

In [22]:
np.abs(v1-v2)

array([3, 3, 3])

In [23]:
#Elementwise multiplication

v1 * v2

array([ 4, 10, 18])

In [24]:
# vector dot product
v1 @ v2

np.int64(32)

In [25]:
np.dot(v1,v2)

np.int64(32)

In [26]:
#vector cross product only applicable for 3 dimension

np.cross(v1,v2)

array([-3,  6, -3])

In [27]:
# scalar multiplication
v1 + 5

array([6, 7, 8])

In [28]:
v1 * 3

array([3, 6, 9])

In [29]:
v1/2

array([0.5, 1. , 1.5])

In [30]:
v1-2

array([-1,  0,  1])

## vector Norms(Distance)

In [31]:
# l2 norm === equlidean distance
np.linalg.norm(v1,ord=2)

np.float64(3.7416573867739413)

In [32]:
##l1 norm  == abosulte distance
np.linalg.norm(v1, ord=1)

np.float64(6.0)

In [33]:
##inf norm == maximum absoulte value
np.linalg.norm(v1,ord=np.inf)

np.float64(3.0)

In [34]:
##unit vector
v1/np.linalg.norm(v1)

array([0.26726124, 0.53452248, 0.80178373])

## vector descriptive

In [35]:
np.sum(v1)

np.int64(6)

In [36]:
v1.sum()

np.int64(6)

In [37]:
v1.mean()

np.float64(2.0)

In [38]:
v1.max()

np.int64(3)

In [39]:
v1.min()

np.int64(1)

In [40]:
v1.argmax() # index of maximum element

np.int64(2)

In [41]:
v1.argmin() # index of minimum element

np.int64(0)

In [42]:
v1.argsort()

array([0, 1, 2])

In [43]:
np.argsort(v1)

array([0, 1, 2])

## cosine similarity

In [44]:
np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))

np.float64(0.9746318461970762)

## sorting

In [45]:
np.sort(v2)

array([4, 5, 6])

In [46]:
v2.sort() # returns nothing rather replace on itself

In [47]:
## Unique

In [48]:
np.unique(v2)

array([4, 5, 6])

In [82]:
v2[v2>3] ## return element > 3

array([4, 5, 6])

In [49]:
v2>3

array([ True,  True,  True])

## vector concatenation

In [50]:
np.concatenate((v1, v2))

array([1, 2, 3, 4, 5, 6])

In [51]:
np.concatenate((v1, v1))

array([1, 2, 3, 1, 2, 3])

## reshaping

In [52]:
v1.reshape((3,1))

array([[1],
       [2],
       [3]])

In [53]:
v1.reshape((1,3))

array([[1, 2, 3]])

In [54]:
v1.reshape((-1,1))

array([[1],
       [2],
       [3]])

In [55]:
v1.reshape((1,-1))

array([[1, 2, 3]])

## flatten

In [56]:
a = v1.reshape((1,-1))

In [57]:
a.flatten()

array([1, 2, 3])

In [58]:
type(v1)

numpy.ndarray

In [59]:
type(a)

numpy.ndarray

## Broadcasting

In [60]:
v1 + 3

array([4, 5, 6])

In [61]:
v2 - 4

array([0, 1, 2])

# matrix operations

In [62]:

a = np.array([
    [1, 2],
    [3, 4]
])

In [63]:
a

array([[1, 2],
       [3, 4]])

In [64]:
a.shape

(2, 2)

In [65]:
rows, cols = a.shape

In [66]:
rows , cols

(2, 2)

## matrix creation

In [67]:
np.eye(3) ## identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [69]:
np.zeros(2)

array([0., 0.])

In [70]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [71]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.diag((2,4,3,5)) , np.diag([2,4,3,5])

(array([[2, 0, 0, 0],
        [0, 4, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 5]]),
 array([[2, 0, 0, 0],
        [0, 4, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 5]]))

## accessing elements

In [73]:
a[1,1]

np.int64(4)

In [74]:
a[0,1]

np.int64(2)

## accessing rows

In [75]:
a[0]

array([1, 2])

In [76]:
a[1]

array([3, 4])

In [77]:
a[-1]

array([3, 4])

In [78]:
a[-2]

array([1, 2])

In [79]:
a[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

## accessing columns

In [80]:
a[: , 0]

array([1, 3])

In [81]:
a[: , 1]

array([2, 4])

In [82]:
a[: , -2]

array([1, 3])

In [83]:
a[: ,  -1]

array([2, 4])

## matrix arithmatic operations

In [84]:
b = np.array([[5,6],[7,8]])

In [85]:
a+b

array([[ 6,  8],
       [10, 12]])

In [86]:
b-a

array([[4, 4],
       [4, 4]])

In [87]:
b-b

array([[0, 0],
       [0, 0]])

In [88]:
5*a

array([[ 5, 10],
       [15, 20]])

In [89]:
3/a

array([[3.  , 1.5 ],
       [1.  , 0.75]])

In [90]:
a/3

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333]])

## elementwise multiplication

In [91]:
a*b

array([[ 5, 12],
       [21, 32]])

## linear algebra operations

## matrix mulitplication

In [92]:
a @ b

array([[19, 22],
       [43, 50]])

In [93]:
a.T @ b

array([[26, 30],
       [38, 44]])

In [94]:
b @ a

array([[23, 34],
       [31, 46]])

In [95]:
a.T @ a

array([[10, 14],
       [14, 20]])

In [96]:
a @ a.T

array([[ 5, 11],
       [11, 25]])

## matix properties

In [97]:
np.linalg.matrix_rank(a) ## no of independent columns

np.int64(2)

In [98]:
np.linalg.matrix_norm(a)

np.float64(5.477225575051661)

In [99]:
np.linalg.matrix_transpose(a)

array([[1, 3],
       [2, 4]])

In [100]:
a.T

array([[1, 3],
       [2, 4]])

In [101]:
np.linalg.matrix_power(a,2) ## a times a ==  a@a here n =2 

array([[ 7, 10],
       [15, 22]])

In [102]:
a@a

array([[ 7, 10],
       [15, 22]])

In [103]:
np.linalg.inv(a) # 1/ad-bc *[cofactor of aij]

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [104]:
np.linalg.det(a) # ad-bc

np.float64(-2.0000000000000004)

In [105]:
np.linalg.trace(a) # sum of diagonal elements

np.int64(5)

## Matrix Decompositions

## Eigen values and eigen vector

In [106]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [107]:
eig_vals , eig_vec = np.linalg.eig(a)

In [108]:
eig_vals, eig_vec

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

## singular values decompostion

In [109]:
u , s , vh = np.linalg.svd(a)

In [110]:
u

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

In [111]:
s ## singular values you have to create diagonal elements with zero array called sigma

array([5.4649857 , 0.36596619])

In [112]:
sigma =  np.diag(s)

In [113]:
vh

array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]])

In [114]:
(u @ sigma) @ vh

array([[1., 2.],
       [3., 4.]])

In [115]:
u @ (sigma @ vh)

array([[1., 2.],
       [3., 4.]])

In [116]:
vh @ (sigma @ u) # order is important

array([[ 1.54714743,  2.75795846],
       [-1.61441471, -4.17057132]])

## Qr decomposition

In [117]:
q , r = np.linalg.qr(a)

In [118]:
q, r

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]),
 array([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))

In [119]:
q @ r

array([[1., 2.],
       [3., 4.]])

## colesky decomposition

In [120]:
np.linalg.cholesky(a)

LinAlgError: Matrix is not positive definite

In [121]:
pd = np.array([[4,2],[2,3]])

In [122]:

np.linalg.cholesky(pd)

array([[2.        , 0.        ],
       [1.        , 1.41421356]])

In [123]:
np.linalg.matrix_rank(pd) , np.linalg.trace(pd) , np.linalg.det(pd) # positive definite rank , det , trace > 0

(np.int64(2), np.int64(7), np.float64(7.999999999999998))

## LU decomposition

In [124]:
la.lu(a)

(array([[0., 1.],
        [1., 0.]]),
 array([[1.        , 0.        ],
        [0.33333333, 1.        ]]),
 array([[3.        , 4.        ],
        [0.        , 0.66666667]]))

## matrix descriptive

In [125]:
a.sum()

np.int64(10)

In [126]:
a.sum(axis=0) #0 for columns

array([4, 6])

In [127]:
a.sum(axis=1) # 1 for rows

array([3, 7])

In [128]:
a.mean()

np.float64(2.5)

In [129]:
a.mean(axis=0) , a.mean(axis=1),  a.mean()

(array([2., 3.]), array([1.5, 3.5]), np.float64(2.5))

In [130]:
a.min(axis=0) , a.min(axis=1)  , a.min()

(array([1, 2]), array([1, 3]), np.int64(1))

In [131]:
a.max(axis=0) , a.max(axis=1)  , a.max()

(array([3, 4]), array([2, 4]), np.int64(4))

In [132]:
a.argmax(axis=1) , a.argmax(axis=0) , a.argmax()

(array([1, 1]), array([1, 1]), np.int64(3))

In [133]:
a.argmin(axis=1) , a.argmin(axis=0) , a.argmin()

(array([0, 0]), array([0, 0]), np.int64(0))

## matrix reshaping

In [134]:
a.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [135]:
a.reshape((1,4))

array([[1, 2, 3, 4]])

In [136]:
a.reshape((1,3))

ValueError: cannot reshape array of size 4 into shape (1,3)

In [137]:
a.flatten()

array([1, 2, 3, 4])

## matrix stacking

In [138]:
np.hstack((a,a))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [139]:
np.vstack((a,a))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [140]:
np.hstack((a , np.array([[1],[2]])))

array([[1, 2, 1],
       [3, 4, 2]])

## matrix splitting

In [141]:
np.hsplit(a , 2) , np.hsplit(a , 1) 

([array([[1],
         [3]]),
  array([[2],
         [4]])],
 [array([[1, 2],
         [3, 4]])])

In [142]:
np.hsplit(a , 4)

ValueError: array split does not result in an equal division

In [143]:
np.vsplit(a , 2)

[array([[1, 2]]), array([[3, 4]])]

In [144]:
np.vsplit(a , 4)

ValueError: array split does not result in an equal division

## matrix concatenation

In [145]:
np.concatenate((a,a))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [146]:
np.concatenate((a,a),axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

## Covariance Matrix

In [147]:
np.cov(a)

array([[0.5, 0.5],
       [0.5, 0.5]])

In [148]:
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

## matrix broadcasting

In [149]:
a+5

array([[6, 7],
       [8, 9]])

In [150]:
a-5

array([[-4, -3],
       [-2, -1]])

## Boolean Indexing

In [151]:
a[a<2]

array([1])

In [152]:
a[a>2]

array([3, 4])

In [153]:
a[(a<2) | (a>2)]

array([1, 3, 4])